apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nutritrace-pod
  name: nutritrace-pod
  namespace: nutritrace
spec:
  containers:
  - image: ghcr.io/traceapps/nutritrace:1.1.0
    name: nutritrace-pod
    ports:
      - containerPort: 3001
        protocol: TCP
    volumeMounts:
      - name: database
        mountPath: /db
      - name: uploads
        mountPath: /uploads
    env:
      - name: DB_PATH
        valueFrom:
          configMapKeyRef:
            name: nutritrace-cm
            key: DB_PATH
      - name: UPLOADS_PATH
        valueFrom:
          configMapKeyRef:
            name: nutritrace-cm
            key: UPLOADS_PATH
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - worker-4
  volumes:
  - name: database
    nfs:
      server: 192.168.1.65
      path: /mnt/pve/bigkev/nutritrace/database
  - name: uploads
    nfs:
      server: 192.168.1.65
      path: /mnt/pve/bigkev/nutritrace/uploads
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
