apiVersion: v1
data:
  DB_PATH: /mnt/pve/bigkev/nutritrace/database/database.db
  UPLOADS_PATH: /mnt/pve/bigkev/nutritrace/uploads
kind: ConfigMap
metadata:
  name: nutritrace-cm
  namespace: nutritrace
