apiVersion: v1
kind: ConfigMap
metadata:
  name: joplin-config-map
  namespace: joplin-namespace
data:
  POSTGRES_PASSWORD: Test@123
  POSTGRES_USER: joplin_user
  POSTGRES_DB: joplin
  APP_BASE_URL: http://192.168.1.79:32300
  APP_PORT: "22300"
  DB_CLIENT: pg
  POSTGRES_HOST: joplin-headless-service
  POSTGRES_PORT: "5432"
