apiVersion: v1
kind: Service
metadata:
  name: joplin-service
  namespace: joplin-namespace
spec:
  type: NodePort
  selector:
    app: joplin-app
  ports:
  - port: 22300
    targetPort: 22300
    nodePort: 32300
