apiVersion: v1
kind: PersistentVolume
metadata:
  name: docmost-pv
  namespace: docmost
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: docmost-storage
  nfs:
    path: /mnt/pve/bigkev/docmost-db
    server: 192.168.1.65
