apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-storage
  namespace: docmost
spec:
  storageClassName: docmost-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
