apiVersion: v1
kind: PersistentVolume
metadata:
  name: docmost-data-pv
  namespace: docmost
spec:
  capacity:
    storage: 10Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: docmost-data-storage
  nfs:
    server: 192.168.1.65
    path: /mnt/pve/bigkev/docmost
