apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bigkev-storage
spec: 
  storageClassName: bigkev-storage
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
