apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bigkev-storage
  namespace: nextcloud-namespace # <--- Always declare the namespace!
spec: 
  storageClassName: bigkev-storage
  accessModes: 
    - ReadWriteMany # <--- Changed to match the PV
  resources:
    requests:
      storage: 5Gi
